version: '3.1'

services:
  db:
    image: mariadb:latest
    container_name: logistics-dev
    ports:
      - 3306:3306
    volumes:
      - "./docker/database:/var/lib/mysql"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=logisticdb